apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "promoteapp.serviceAccountName" . }}
  labels:
    {{- include "promoteapp.labels" . | nindent 4 }}
secrets:
  - name: {{ .Values.registry.secret.name }}
